// Featured products data for the presentation page
export const featuredProducts = {
    '700': {
        model: '700',
        fullName: 'ErgoPack 700',
        tagline: 'Zero Electricity. Pure Precision.',
        description: 'Manual Hand-Crank Strapping Tool',
        category: 'Manual Operation',
        heroStat: {
            value: '64.4',
            unit: 'kg',
            label: 'Ultra-Light Weight',
        },
        specs: {
            weight: 64.4,
            palletWidth: { min: 30, max: 255 },
            palletHeight: { min: 10, max: 230 },
            chainLength: 6,
            operation: 'Manual Hand Crank',
        },
        highlights: [
            'No battery required',
            'Zero maintenance costs',
            'Multi-material compatible',
            'AGR Certified ergonomics',
            'Perfect for low-volume operations',
        ],
        materials: ['PP', 'PET', 'Paper', 'Cord', 'Composite'],
        color: '#C8102E',
        image: '/images/products/700/0.jpg',
    },
    GO: {
        model: 'GO',
        fullName: 'ErgoPack GO',
        tagline: 'Mobility Without Compromise.',
        description: 'Economy Portable Pallet Strapping System',
        category: 'Economy Portable',
        heroStat: {
            value: '350',
            unit: 'cycles',
            label: 'Per Charge',
        },
        specs: {
            weight: 90,
            chainSpeed: 40,
            cycles: 350,
            chargingTime: '8-10 hours',
            palletWidth: { min: 30, max: 240 },
            palletHeight: { min: 80, max: 190 },
        },
        highlights: [
            'Joystick control',
            '40 m/min chain speed',
            'Standard Tool-Lift included',
            'Multi-material support',
            'Best value for mobility',
        ],
        materials: ['PP', 'PET', 'Paper', 'Cord', 'Composite'],
        color: '#4A90D9',
        image: '/images/products/GO/0.jpg',
    },
    '726X': {
        model: '726X Li',
        fullName: 'ErgoPack 726X Li',
        tagline: 'The Future is Lithium.',
        description: 'Professional Lithium-Ion Strapping System',
        category: 'X-pert Line',
        heroStat: {
            value: '1200',
            unit: 'cycles',
            label: 'Per Charge',
        },
        specs: {
            weight: 104,
            chainSpeed: 66,
            cycles: 1200,
            chargingTime: '3.5 hours',
            tension: { min: 400, max: 2500 },
            palletWidth: { min: 40, max: 270 },
            palletHeight: { min: 10, max: 230 },
        },
        highlights: [
            'Lithium-Ion technology',
            '66 m/min chain speed',
            'Siemens Touchscreen',
            'Line Laser Type 2',
            '3x more cycles than Economy',
        ],
        advantages: [
            { label: '3.4x More Cycles', detail: '1200 vs 350' },
            { label: '60% Faster Charging', detail: '3.5h vs 8-10h' },
            { label: '60% Lighter Battery', detail: '5kg vs 12.3kg' },
        ],
        color: '#FFB81C',
        image: '/images/products/726X/0.jpg',
    },
};

export const comparisonData = [
    { feature: 'Operation', '700': 'Manual Crank', GO: 'Battery Powered', '726X': 'Lithium-Ion' },
    { feature: 'Weight', '700': '64.4 kg', GO: '90 kg', '726X': '104 kg' },
    { feature: 'Chain Speed', '700': 'Manual', GO: '40 m/min', '726X': '66 m/min' },
    { feature: 'Cycles/Charge', '700': '∞', GO: '350', '726X': '1200' },
    { feature: 'Charging Time', '700': 'N/A', GO: '8-10 hours', '726X': '3.5 hours' },
    { feature: 'Touchscreen', '700': '—', GO: '—', '726X': '✓ Siemens' },
    { feature: 'Line Laser', '700': '—', GO: '—', '726X': '✓ Type 2' },
    { feature: 'Best For', '700': 'Low Volume', GO: 'Value + Mobility', '726X': 'High Performance' },
];

export type ProductKey = '700' | 'GO' | '726X';
